### ISSUE TITLE
multilevel cache feature

### ISSUE THREAD

**Issue by seaguest** [patrickmn/go-cache#101]
Hello,

Multilevel cache (go-cache + redis) will be quite useful in server cluster case,  will this be in the plan?

Is there any good solution for multilevel cache solution?

**Comment by patrickmn** [comment]
To be honest, in this case it would probably be better to use a Redis client library that does in-memory caching (assuming that that actually exists). But you could implement something that queries go-cache before querying redis. It's not in scope for the library itself though.
