### ISSUE TITLE
CacheGetManyConcurrent tests has incorrect key

### ISSUE THREAD

**Issue by Gobd** [patrickmn/go-cache#111]
I think these two lines should be `k := "foo" + strconv.Itoa(i)` (i instead of n) so that each key is different. This will make the sharded cache look better since keys will be able to spread out.

- https://github.com/patrickmn/go-cache/blob/master/sharded_test.go#L68
- https://github.com/patrickmn/go-cache/blob/master/cache_test.go#L1558

**Comment by patrickmn** [comment]
Yep, you're right. What a weird mistake -- thanks for noticing it. Will fix shortly.
