### ISSUE TITLE
Provide a way to distinguish "not found" from "wrong type" for incr/decr methods

### ISSUE THREAD

**Issue by autarch** [patrickmn/go-cache#14]
These are two very different error cases. In my use case, I don't really care if the item's not found (that just means it has expired) but I _do_ care if it's not the type I expect.

It'd be nice if there was a way to distinguish the two. I think the only way to do that without serious API breakage would be to return two different error types. I'd be up for working on a PR if you'd be interested in changing this.

**Comment by patrickmn** [comment]
Now that it's almost 2020, my opinion has changed to "we don't try to handle 'wrong type' anywhere else, so this shouldn't be a special case".
