### ISSUE TITLE
Refresh value callback

### ISSUE THREAD

**Issue by pbdeuchler** [patrickmn/go-cache#21]
It would be awesome to have a callback, similar to [groupcache's `OnEvicted`](https://github.com/golang/groupcache/blob/master/lru/lru.go#L23) which can automatically refresh a value upon expiry.

**Comment by pmylund** [comment]
I like it. I'll implement it soon. Sorry for the delay.

**Comment by patrickmn** [comment]
Added in https://github.com/patrickmn/go-cache/commit/3f2c810ea19ac967a5435d943ce437b446a84b4c

**Comment by pbdeuchler** [comment]
This is awesome, much obliged!
