### ISSUE TITLE
Efficient deletion

### ISSUE THREAD

**Issue by beppeben** [patrickmn/go-cache#25]
Have you thought about introducing (as an option, maybe) a binary tree into the cache structure, with items arranged in sorted order according to their expiration? This could avoid going through all the items when deleting expired ones. I might give it a try if anyone is interested.

**Comment by pmylund** [comment]
I did think about it, and I've always been a little nervous about the write lock being held during these scans.

If you can implement this without meaningfully reducing performance in the benchmarks (I'm a little nervous about how Set would perform when the cache is large,) and without adding memory overhead much greater than a binary tree containing the expiration times and keys, I would definitely be open to merging it and just making it the default. I'm not sure it makes sense to make it an option if it's not actually better most of the time. It would be too confusing.

It would also be helpful to have a benchmark comparing the old and new algorithms with a large, populated cache that has only a few expired items. I would expect that the binary tree approach wins out every time, but I'm not sure (cache locality and all.)

Here's a few potential problems:

  - If I set "foo" with some value that expires in one minute, wait 30 seconds, then set "foo" again with an expiration of one minute, "foo" mustn't expire prematurely. Same thing if I delete it and set it. The solution is probably to verify the item's expiration time before deleting, and not relying on the key in the tree to be the "current" expiration time.

  - Items can have identical expiration times. A BST which allows duplicates would be preferable to using slices as values, I think.

**Comment by patrickmn** [comment]
I made a change, https://github.com/patrickmn/go-cache/commit/901b2413eec5582e8dfaff57e290ae210be96d6b, to improve cache locality which helped:

Before:

BenchmarkCacheGet	100000000	        23.9 ns/op
BenchmarkRWMutexMapGet	100000000	        17.5 ns/op
BenchmarkCacheGetConcurrent	100000000	        24.1 ns/op
BenchmarkRWMutexMapGetConcurrent	100000000	        18.0 ns/op
BenchmarkCacheGetManyConcurrent	100000000	        26.1 ns/op
BenchmarkCacheSet	10000000	       204 ns/op
BenchmarkRWMutexMapSet	50000000	        45.5 ns/op
BenchmarkCacheSetDelete	10000000	       252 ns/op
BenchmarkRWMutexMapSetDelete	20000000	        96.9 ns/op
BenchmarkCacheSetDeleteSingleLock	10000000	       232 ns/op
BenchmarkRWMutexMapSetDeleteSingleLock	50000000	        72.4 ns/op
*BenchmarkDeleteExpired	10000000	       378 ns/op*
BenchmarkShardedCacheGet	50000000	        39.4 ns/op
BenchmarkShardedCacheGetManyConcurrent	50000000	        40.4 ns/op

After:

BenchmarkCacheGet	100000000	        27.7 ns/op
BenchmarkRWMutexMapGet	100000000	        17.5 ns/op
BenchmarkCacheGetConcurrent	50000000	        30.5 ns/op
BenchmarkRWMutexMapGetConcurrent	100000000	        17.7 ns/op
BenchmarkCacheGetManyConcurrent	50000000	        30.6 ns/op
BenchmarkCacheSet	20000000	       152 ns/op
BenchmarkRWMutexMapSet	50000000	        44.1 ns/op
BenchmarkCacheSetDelete	10000000	       211 ns/op
BenchmarkRWMutexMapSetDelete	20000000	        96.0 ns/op
BenchmarkCacheSetDeleteSingleLock	10000000	       185 ns/op
BenchmarkRWMutexMapSetDeleteSingleLock	50000000	        71.6 ns/op
*BenchmarkDeleteExpired	10000000	       175 ns/op*
BenchmarkShardedCacheGet	50000000	        43.2 ns/op
BenchmarkShardedCacheGetManyConcurrent	50000000	        42.8 ns/op

**Comment by beppeben** [comment]
Hi Patrick,
As for your first remark, yes the new set operation would need to check if the item is in the cache, remove it from the tree and then reinsert it. This may be costly if the cache is large, but I was also thinking that the operations on the BST might be done asyncronously (the BST having its own lock), so that the "set" running time is (mostly) unaffected. 
I will do some experiments as soon as I have some time!

**Comment by beppeben** [comment]
just did a little experiment in my "bst" fork of your project. I just modified the "set" and "delete expired" functions for now. Here "BenchmarkLargeCacheXY" tests a repeated set operation on a cache with deletion interval equal to X.Y% of the expiration time. I still need to double check and do things more properly, but the results seem promising.

before:
BenchmarkDeleteExpiredLoop-4                       	     500	   2817519 ns/op
BenchmarkLargeCache01-4                            	 1000000	    139636 ns/op
BenchmarkLargeCache02-4                            	 1000000	     78410 ns/op
BenchmarkLargeCache05-4                            	 1000000	     21646 ns/op
BenchmarkLargeCache10-4                            	 1000000	      8247 ns/op
BenchmarkLargeCache20-4                            	 1000000	      4942 ns/op
BenchmarkLargeCache50-4                            	 1000000	      2754 ns/op

after:
BenchmarkDeleteExpiredLoop-4                       	 5000000	       281 ns/op
BenchmarkLargeCache01-4                            	 1000000	      3066 ns/op
BenchmarkLargeCache02-4                            	 1000000	      2106 ns/op
BenchmarkLargeCache05-4                            	 1000000	      1799 ns/op
BenchmarkLargeCache10-4                            	 1000000	      2060 ns/op
BenchmarkLargeCache20-4                            	 1000000	      1891 ns/op
BenchmarkLargeCache50-4                            	 1000000	      1916 ns/op

**Comment by beppeben** [comment]
hum well I already noticed some bugs in my code, I will revise it and send you a pull request when it's double checked.

**Comment by chenjie4255** [comment]
so is there any progress?

**Comment by patrickmn** [comment]
Closing for now.
