### ISSUE TITLE
panic: RUnlock of unlocked RWMutex when replacing expired item

### ISSUE THREAD

**Issue by tedjp** [patrickmn/go-cache#28]
Hi, "Inlining" of  get and Expired has introduced a panic in Add() when replacing an expired object.

```
// Add an item to the cache only if an item doesn't already exist for the given
// key, or if the existing item has expired. Returns an error otherwise.
func (c *cache) Add(k string, x interface{}, d time.Duration) error {
    c.mu.Lock()
    _, found := c.get(k)
```

Then we see the implementation of get():
```
func (c *cache) get(k string) (interface{}, bool) {
    item, found := c.items[k]
    if !found {
        return nil, false
    }
    // "Inlining" of Expired
    if item.Expiration > 0 {
        if time.Now().UnixNano() > item.Expiration {
            c.mu.RUnlock()
            return nil, false
```

The Add() function acquired a write lock (RWMutex.Lock()), but if there's an expired object with the same key, the "inlined" code calls RWMutex.RUnlock() - but it was the write-lock that was held, not a read-lock.

**Comment by patrickmn** [comment]
Argh! Thanks for catching this. `get` should not be messing with locks at all.

Fixed in https://github.com/patrickmn/go-cache/commit/5849ccb30876239377aca783d5d9546f3876020e

**Comment by tedjp** [comment]
Wonderful, thanks!

As  a side note, you could use `defer c.mu.RUnlock()` after the initial RLock() call in all the exported functions if you want to avoid having to repeat it before every `return` statement. Similarly for Lock/Unlock.

**Comment by patrickmn** [comment]
I'd like to, but last I checked that didn't produce the same code: defer would add ~200ns to operations and using `expired` and `get` functions (so no "inlining") similarly added ~100ns. That's significant when the base function itself only takes ~50-70ns.

Maybe when the compiler does inlining better, and defer is implemented differently (right now I think it's essentially a slice of functions that's appended to and then looped through when exiting the function.
