### ISSUE TITLE
Semantic Versions (tags)

### ISSUE THREAD

**Issue by tedjp** [patrickmn/go-cache#30]
It would be great to be able to pin to a particular version of go-cache using gopkg.in for versioning.

Basically I'm just asking to have something tagged as version 1.0 :-)

Details: http://gopkg.in/

**Comment by onlyjob** [comment]
+1. Please tag formal releases. 
Tags/releases are quite useful for downstream package maintainers (in [Debian](http://debian.org) and other distributions) to export source tarballs, automatically track new releases and to declare dependencies between packages. Read more in the [Debian Upstream Guide](https://wiki.debian.org/UpstreamGuide#Releases_and_Versions).

Thank you.

See also https://en.wikipedia.org/wiki/Software_versioning

**Comment by patrickmn** [comment]
I added 1.0.0 and 2.0.0. 2 is faster with roughly (though not exactly) the same API.

**Comment by onlyjob** [comment]
Thanks. :)
