### ISSUE TITLE
Feature request: Ensure single OnEvicted call

### ISSUE THREAD

**Issue by janekolszak** [patrickmn/go-cache#33]
Hi!
OnEvicted is an awesome idea, but it lacks one key feature - synchronization.

The callback will be called outside any locks so it's possible couple of threads will try to populate the cache at the same time.

There is no issue if only the janitor calls onEvicted.

**Comment by patrickmn** [comment]
I'm not sure what you mean. The OnEvicted function will only be called once for each item that has expired, so you wouldn't ever be refreshing the same key more than once at the same time.
