### ISSUE TITLE
Qs: get all keys and values at a given time

### ISSUE THREAD

**Issue by mg03** [patrickmn/go-cache#51]
Is there a way to range over a cache object and get its key and values ?

**Comment by patrickmn** [comment]
Yes: https://godoc.org/github.com/patrickmn/go-cache#Cache.Items

**Comment by mg03** [comment]
I tried something like this

```
	for i, val := range grouppathcache.Items() {
		fmt.Println(fmt.Sprintf("Group path cache index is %v and object is %v", i, val.Object.(string)))
	}
```

But nothing shows up. I did a 

 `fmt.Println(fmt.Sprintf("No of items in grouppathcache are %i", grouppathcache.ItemCount()))`

and i get 18 which is what i expect

**Comment by patrickmn** [comment]
Items() only returns unexpired items, while ItemCount() will tell you how many items (expired or unexpired are in the cache.) Could it be that those 18 items have already expired?

**Comment by mg03** [comment]
I have initiated the cache as follows:
`grouppathcache = cache.New(-1, -1)`   - I thought this meant no expiration and no removal
and then each element is added like so
`grouppathcache.Set(k, path, cache.NoExpiration)`

With these 2 , i believe no items should ever expire ... am i wrong here ?
My use case is that the cache should never invalidate/expire unless I explicitly tell it to do so and/or remove it manually

**Comment by patrickmn** [comment]
That should work.

Could you provide a complete example that demonstrates the problem?

**Comment by mg03** [comment]
OK, let me try to get a self sufficient piece of code ..
