### ISSUE TITLE
Accidental dereference causes janitor to shut down

### ISSUE THREAD

**Issue by timboldt** [patrickmn/go-cache#54]
A colleague of mine fell into the following trap:

var myCache cache.Cache
...
myCache = *cache.New(...)

This of course triggers the finalizer which shuts down the janitor and results in a memory leak.

**Comment by patrickmn** [comment]
Don't do that :)

**Comment by timboldt** [comment]
I figured that at least documenting it as an "issue" would help the next person who stumbled on it.

But yeah, don't do that. :-)
