### ISSUE TITLE
About time to tag a new release?

### ISSUE THREAD

**Issue by peterhellberg** [patrickmn/go-cache#67]
The [dep](https://github.com/golang/dep) vendoring tool use the latest tag instead of `master` by default. 

Right now the latest tag (`v2.0.0`)  for this package is over a year old.

**Comment by patrickmn** [comment]
go-cache is mostly stable and does its job well, so regular releases for releases' sake isn't necessary. (PRs still need to be reviewed but they are not merged at the moment.)

Perhaps when there fixes or a few more features in the pipe.

**Comment by peterhellberg** [comment]
But there has been changes to the public API since the v2.0.0 tag, and not tagging a release means that users of `dep` will default to using a version of go-cache without SetDefault for example.

**Comment by patrickmn** [comment]
https://github.com/patrickmn/go-cache/releases/tag/v2.1.0
