### ISSUE TITLE
Data Race

### ISSUE THREAD

**Issue by marcosrmendezthd** [patrickmn/go-cache#68]
2017/09/25 14:24:31 WARNING: DATA RACE
2017/09/25 14:24:31 Write at 0x00c420063c50 by goroutine 27:
2017/09/25 14:24:31   runtime.mapdelete_faststr()
2017/09/25 14:24:31       /usr/local/go/src/runtime/hashmap_fast.go:801 +0x0
2017/09/25 14:24:31   ...s/vendor/github.com/patrickmn/go-cache.(*cache).DeleteExpired()
2017/09/25 14:24:31       ...s/vendor/github.com/patrickmn/go-cache/cache.go:885 +0x318
2017/09/25 14:24:31   github.homedepot.com/ose-platform/nos/vendor/github.com/patrickmn/go-cache.(*janitor).Run()
2017/09/25 14:24:31       ...s/vendor/github.com/patrickmn/go-cache/cache.go:1039 +0xdd

2017/09/25 14:53:13 Goroutine 27 (running) created at:
2017/09/25 14:53:13   ...s/vendor/github.com/patrickmn/go-cache.runJanitor()
2017/09/25 14:53:13       ...s/vendor/github.com/patrickmn/go-cache/cache.go:1056 +0xf2
2017/09/25 14:53:13  ...s/vendor/github.com/patrickmn/go-cache.newCacheWithJanitor()
2017/09/25 14:53:13      ..s/vendor/github.com/patrickmn/go-cache/cache.go:1079 +0x167
2017/09/25 14:53:13   ...s/vendor/github.com/patrickmn/go-cache.New()
2017/09/25 14:53:13       ...s/vendor/github.com/patrickmn/go-cache/cache.go:1092 +0x7b

**Comment by patrickmn** [comment]
I think this was fixed by https://github.com/patrickmn/go-cache/pull/64 ?

**Comment by marcosrmendezthd** [comment]
ok. let me pull from master. using glide so it's using the last release by semantic version. commit 1881a9bccb818787f68c52bfba648c6cf34c34fa

**Comment by patrickmn** [comment]
Ah. I should've cut a new release after this bug was fixed. Will make a new release soon.

**Comment by marcosrmendezthd** [comment]
that did it. thank you!!!!
