### ISSUE TITLE
less than one purging time not respected

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [patrickmn/go-cache#69]
### Summary

Setting up a cache with `cleanup_interval` less than 1, after an item expires, I am no longer able to `Get` it.

### Steps to reproduce

The following is a minimal working example illustrating the problem:

```
package main

import (
	"fmt"
	"github.com/patrickmn/go-cache"
	"time"
)

func main() {
	duration := time.Duration(-1) * time.Nanosecond
	fmt.Println(duration < 0)
	cache := cache.New(5*time.Second, duration)
	cache.SetDefault("foo", "bar")
	for {
		item, found := cache.Get("foo")
		if found {
			fmt.Println("Found it!" + item.(string))
			time.Sleep(time.Second)
		} else {
			fmt.Println("Key not found!")
			return
		}
	}
}
```

### Experienced behaviour

After the item expires, `Get` returns a `found` boolean of false, indicating that the item cannot be found.

### Expected behaviour

The item should still be found, as the janitor should be disabled, as a less than 1 cleanup interval was specified on creation of the cache.

Am I doing something wrong, or misunderstanding something?

**Comment by valentin-krasontovitsch** [comment]
Hm, yeah, just found this after inspecting `Get` - so that's intended behaviour? Sorry, I'm a bit new to caches...

**Comment by patrickmn** [comment]
"janitor" isn't really a general cache concept, but yes, generally caches don't return an item that has expired, even if it's still pending cleanup (which is what the janitor does at regular intervals.)

**Comment by valentin-krasontovitsch** [comment]
Okai, thanks for the explanation!

**Comment by patrickmn** [comment]
Thanks for using go-cache! :)
