### ISSUE TITLE
no values returned

### ISSUE THREAD

**Issue by SaifSalah** [patrickmn/go-cache#73]
hello,

this is my code

var C = cache.New(50*time.Minute, 50*time.Minute)

func getFromMemory()   {

	foo,found := C.Get("foo")

	if !found{

		fmt.Println("Nil")
	}else {
		fmt.Println(foo,found)
	}

}

func insertToMem()  {

	ip := []string{"192.168.1.1","192.168.1.2","192.168.1.3","192.168.1.5","192.168.1.15"}
	Time := []string{time.Now().String(),time.Now().String(),time.Now().String(),time.Now().String(),time.Now().String()}
	tsVal := []string{"123","123","123","123","123"}

	saif := test{Ip:ip,Time:Time,TsVal:tsVal}

	Get := New{}

	for _,val := range saif.Ip{

		Get.Foo[0] = val

		for _,getTime := range saif.Time{

			Get.Foo[1] = getTime
		}

		for _,tsVal := range saif.TsVal{
			Get.Foo[2] = tsVal
		}

		C.Set("foo", Get.Foo,cache.DefaultExpiration)

	}

}

func main()  {

	//insertToMem()
	getFromMemory()

}

no values return when comment [ insertToMem ] Method

**Comment by lozaeric** [comment]
If you don't insert values, the cache is empty. Am I missing something ?

**Comment by patrickmn** [comment]
I don't understand the example. Please reproduce the issue completely in one file/block if this is still relevant.
