### ISSUE TITLE
Iteration based on "prefix"

### ISSUE THREAD

**Issue by rebootcode** [patrickmn/go-cache#74]
Is it possible to Iterate item with just providing "prefix" of the key. Just like Badger - https://github.com/dgraph-io/badger#prefix-scans

**Comment by newm4n** [comment]
As we cache web page using the URL's path, I cached something with keys like /foo/bar and /foo/bar/baz . So removing cache /foo/bar should be able to remove /foo/bar cache and /foo/bar/*/**. At least the we could have something like

```
func (c *Cache) AllKeys() []string {
    var ret []string
    for i,_ := range c.items {
        ret = append(ret, i)
    }
    return ret
}
```

So we can iterate of all cached keys.

**Comment by lozaericml** [comment]
I have a similar use-case. I'm thinking of creating a pull request.

**Comment by lozaeric** [comment]
At the moment, It's not possible.

I have a similar use-case. I'm thinking of creating a pull request.
