### ISSUE TITLE
Get 'EOF' error in LoadFile

### ISSUE THREAD

**Issue by ghost** [patrickmn/go-cache#76]
SaveFile to disk
And LoadFile get EOF error.

**Comment by MrVine** [comment]
This issue should be closed, because methods `c.SaveFile()` and `c.LoadFile` is deprecated and probably will be deleted in the future.

**Comment by patrickmn** [comment]
Please provide example code to reproduce this issue if this is still relevant. The methods are indeed deprecated but should still work.
