### ISSUE TITLE
Time to IDLE and Time to Live

### ISSUE THREAD

**Issue by NoahShen** [patrickmn/go-cache#9]
The defaultExpiration when createing new cache is the time to live. Will go-cache support time to IDLE? 

e.g for now defaultExpiration = 10 seconds, item will be removed after 10 seconds no matter how much time item was accessed.
If time to IDLE is supported, item's expiration will be reset when it's accessed

Thanks.

**Comment by patrickmn** [comment]
This doesn't exactly do what you proposed, but adds LRU functionality to cap the size of the cache: https://github.com/patrickmn/go-cache/pull/17
