### ISSUE TITLE
Replace time.Now() by runtime.nanotime()

### ISSUE THREAD

**Issue by larytet** [patrickmn/go-cache#90]
* time.Time is 24 bytes. int64 returned by nanotime() is 8 bytes. This one is not relevant for the code - item.Expiration is int64 already.  
* runtime.nanotime() is 2x faster

```
import	_ "unsafe" // required to use //go:linkname

//go:noescape
//go:linkname nanotime runtime.nanotime
func nanotime() int64

// time.Now() is 45ns, runtime.nanotime is 20ns
// I can not create an exported symbol with //go:linkname
// I need a wrapper
// Go does not inline functions? https://lemire.me/blog/2017/09/05/go-does-not-inline-functions-when-it-should/
// The wrapper costs 5ns per call
func Nanotime() int64 {
	return nanotime()
}
```

Using 1ms resolution we can potentially save 4 bytes more.

**Comment by larytet** [comment]
100-200ns per Store/Load is probably the fastest golang can do
This is the trivial implementation using map[int64]int64  https://github.com/larytet/mcachego

**Comment by logrusorgru** [comment]
> Using 1ms resolution we can potentially save 4 bytes more.

For a 64-bit architecture it doesn't matter, since a data in structures is aligned by 64-bit (8 byte).

```go
package main

import (
	"fmt"
	"unsafe"
)

type Item32 struct {
	Object     interface{} // 8+8 or 4+4
	Expiration int32
}

type Item64 struct {
	Object     interface{} // 8+8 or 4+4
	Expiration int64
}

func main() {
	fmt.Println(unsafe.Sizeof(Item32{}))
	fmt.Println(unsafe.Sizeof(Item64{}))
}
```

For amd64,
```
24
24
```

For 32-bit [NaCl](https://blog.golang.org/playground) on [play.golagn.org](https://play.golang.org/p/CSc1qOM7whg).

```
12
16
```
---

Note: the NaCl is not a real hardware.

**Comment by larytet** [comment]
@logrusorgru , you are right of course. The trick can make sense if bit fields are used. 
In my simple example I care more about performance than memory. 

It appears that the cache miss dominates the performance. It would not surprise me to find the bit fields  faster than the aligned fields for some table sizes.

**Comment by patrickmn** [comment]
IMO the voodoo code isn't worth it.

Howcome this didn't happen upstream, e.g. by exporting nanotime? Related: https://github.com/golang/go/issues/16658
